name: mmg-payload-plugin Package

on:
  push:

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
        env:
          FONT_TOKEN: ${{ secrets.FONT_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: sed -i.back "s|PAT_SECRET|${FONT_TOKEN}|g" .npmrc
      - run: echo $NODE_AUTH_TOKEN
      - run: echo $FONT_TOKEN
      - run: cat .npmrc
      - run: yarn
      - run: yarn build
      - run: yarn publish
